version: "3.8"
networks:
  graylog:
    driver: bridge
services:
  mongodb:
    image: "mongo:4.4"
    volumes:
      - "PathToMongoDBFolder:/data/db"
    restart: "on-failure"
    ports:
      - 27017:27017
    networks:
      - graylog
  
  opensearch:
    image: opensearchproject/opensearch:1.3.1
    restart: "on-failure"
    environment:
      - plugins.security.disabled=true
      - node.name=graylog-server
      - cluster.name=graylog
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - graylog
  
  graylog:
    hostname: "server"
    image: graylog/graylog:4.3.13
    depends_on:
      - opensearch
      - mongodb
    links:
      - mongodb
      - opensearch
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      GRAYLOG_ROOT_PASSWORD_SHA2: "415e8a6ba1c3eb93e81df34731acc3d60efee685c8e6f7412592a45ba3a0e3b0"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "9000:9000"
    - "1514:1514"
    - "5044:5044"
    - "5044:5044/udp"
    - "1514:1514/udp"
    - "12201:12201"
    - "12201:12201/udp"
    volumes:
      - "PathToGrayLogDataFolder:/usr/share/graylog/data"
    restart: "on-failure"
    networks:
      - graylog
